let games = [
    "Titanfall 2",
    "Post Void",
    "GoNNER",
    "Hotline Miami",
    "Satisfactory",
    "Apex Legends",
    "Counter Strike: Global Offensive",
    "Among Us",
    "Fall Guys",
    "Minecraft",
    "DOOM",
    "Elite Dangerous",
    "Hylics",
    "Hylics 2",
    "VVVVVV",
    "Super Hexagon",
    "Rocket League",
    "Team Fortress 2",
    "DOOM Eternal",
    "Hollow Knight",
    "Garry's Mod",
    "Subnautica",
    "Subnautica: Below Zero",
    "Enter the Gungeon",
    "Intralism",
    "Hotline Miami 2: Wrong Number",
    "GONNER2",
    "Phasmophobia",
    "Quaver",
    "Deceit",
    "Paunch",
    "Dead by Daylight",
    "Beat Saber",
    "Half-Life",
    "Half-Life 2",
    "OMORI",
    "Raft",
    "Terraria"
];

let ball = [
    "As I see it, yes",
    "Ask again later",
    "Better not tell you now",
    "Cannot predict now",
    "Concentrate and ask again",
    "Don't count on it",
    "It is certain",
    "It is decidedly so",
    "Most likely",
    "My reply is no",
    "My sources say no",
    "Outlook not so good",
    "Outlook good",
    "Reply hazy, try again",
    "Signs point to yes",
    "Very doubtful",
    "Without a doubt",
    "Yes",
    "Yes, definitely",
    "You may rely on it"
];

module.exports = {
    games,
    ball,
    guildOnly: "This action is restricted to guilds only.",
    empty: "Missing required arguments.",
    perms: "I have insufficient permissions to preform this action.",
    target: "Please mention a user to target.",
    noshow: "Nothing to show.",
    expression: "Invalid expression"
};
